site_name: Sonic Docs
site_url: https://sonicdocs.github.io/
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  palette:
    - scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
    - scheme: default
      primary: blue
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
